name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: The module deployment wizard crashes when...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The module should deploy successfully...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I see an error message...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or paste URLs

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: "120.0.6099.129"

  - type: input
    id: ui-version
    attributes:
      label: Operator UI Version
      description: What version of the Operator UI are you using?
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: input
    id: operator-version
    attributes:
      label: Forkspacer Operator Version
      description: What version of the Forkspacer operator is running?
      placeholder: "v0.1.3"

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any other relevant environment information
      placeholder: |
        - OS: macOS 14.0
        - Kubernetes version: 1.28
        - Deployment method: Helm

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, paste any relevant logs or error messages
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
