name: Question
description: Ask a question about usage or configuration
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? Please fill out the form below.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've already tried
      placeholder: I'm trying to... I've already looked at...

  - type: input
    id: version
    attributes:
      label: Operator UI Version
      description: What version are you using?
      placeholder: "v0.1.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
