replicaCount: 1

# Image configuration - will be overridden by global values from parent chart
image:
  repository: "ghcr.io/forkspacer/operator-ui"
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

# Global configuration for compatibility with parent chart
global:
  operatorUI:
    image:
      repository: "ghcr.io/forkspacer/operator-ui"
      pullPolicy: IfNotPresent
      tag: "v0.1.1"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  # nodePort: 30080  # Only used when type is NodePort

# Ingress is handled by the parent chart with unified routing
# The parent chart routes /* to this service

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  # API server URL for nginx server-side proxying (internal cluster service)
  API_SERVER_URL: "http://forkspacer-api-server:8080"
  # Leave REACT_APP_API_BASE_URL empty to use relative paths (/api/v1)
  # which nginx will proxy to API_SERVER_URL
  REACT_APP_API_BASE_URL: ""

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}